# sudo service docker start
version: '3.1'

services:
  db:
    image: postgres
    volumes:
      - ./db/docker-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  app:
    image: mpetrus/nestjs-task-man:1
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}

  adminer:
    depends_on:
      - db
    image: adminer
    ports:
      - 8080:8080
