# sudo service docker start
# docker-compse -f docker-compose.dev.yml up
version: '3.1'

services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db

  adminer:
    depends_on:
      - db
    image: adminer
    ports:
      - 8080:8080
