# sudo service docker start
# docker-compse -f docker-compose.dev.yml up
version: '3.1'

services:
  db:
    image: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  adminer:
    depends_on:
      - db
    image: adminer
    ports:
      - 8080:8080
