# sudo service docker start
version: '3.1'

services:
  db:
    image: postgres
    volumes:
      - ./db/docker-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  adminer:
    depends_on:
      - db
    image: adminer
    ports:
      - 8080:8080
