# sudo service docker start
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./docker-data/task-management:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8080:8080
